"""
Handles final delivery of content to clients via email and Notion
"""

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Optional
import requests

class DeliveryManager:
    """Manages content delivery to clients"""
    
    def __init__(self, smtp_config: dict, notion_token: Optional[str] = None):
        self.smtp_config = smtp_config
        self.notion_token = notion_token
    
    def deliver_via_email(self, recipient: str, subject: str, content: str, sender_name: str = "AI Content Team") -> bool:
        """Send completed content via email"""
        msg = MIMEMultipart('alternative')
        msg['Subject'] = subject
        msg['From'] = f"{sender_name} <{self.smtp_config['from_email']}>"
        msg['To'] = recipient
        
        # HTML version
        html = f"""
        <html>
        <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <div style="background: #f8f9fa; padding: 20px; border-radius: 8px;">
                <h2 style="color: #333;">Your Content is Ready</h2>
                <p>Here's the completed content as requested:</p>
                <div style="background: white; padding: 20px; border-radius: 4px; margin: 15px 0;">
                    {content.replace(chr(10), '<br>')}
                </div>
                <p style="color: #666; font-size: 12px;">
                    This content was generated by AI and reviewed by our editorial team.
                </p>
            </div>
        </body>
        </html>
        """
        
        msg.attach(MIMEText(content, 'plain'))
        msg.attach(MIMEText(html, 'html'))
        
        try:
            with smtplib.SMTP(self.smtp_config['host'], self.smtp_config['port']) as server:
                server.starttls()
                server.login(self.smtp_config['username'], self.smtp_config['password'])
                server.send_message(msg)
            return True
        except Exception as e:
            print(f"Email delivery failed: {e}")
            return False
    
    def deliver_via_notion(self, database_id: str, title: str, content: str, tags: list[str] = None) -> bool:
        """Create a Notion page with the completed content"""
        if not self.notion_token:
            print("Notion token not configured")
            return False
        
        headers = {
            "Authorization": f"Bearer {self.notion_token}",
            "Content-Type": "application/json",
            "Notion-Version": "2022-06-28"
        }
        
        # Convert markdown to Notion blocks
        blocks = self._markdown_to_notion_blocks(content)
        
        data = {
            "parent": {"database_id": database_id},
            "properties": {
                "title": {
                    "title": [{"text": {"content": title}}]
                },
                "Status": {
                    "select": {"name": "Ready for Review"}
                },
                "Tags": {
                    "multi_select": [{"name": tag} for tag in (tags or ["AI Generated"])]
                }
            },
            "children": blocks
        }
        
        response = requests.post(
            "https://api.notion.com/v1/pages",
            headers=headers,
            json=data
        )
        
        return response.status_code == 200
    
    def _markdown_to_notion_blocks(self, markdown: str) -> list:
        """Convert markdown text to Notion block structure"""
        blocks = []
        lines = markdown.split('\n')
        
        for line in lines:
            if line.startswith('## '):
                blocks.append({
                    "object": "block",
                    "type": "heading_2",
                    "heading_2": {
                        "rich_text": [{"type": "text", "text": {"content": line[3:]}}]
                    }
                })
            elif line.startswith('# '):
                blocks.append({
                    "object": "block",
                    "type": "heading_1",
                    "heading_1": {
                        "rich_text": [{"type": "text", "text": {"content": line[2:]}}]
                    }
                })
            elif line.startswith('- '):
                blocks.append({
                    "object": "block",
                    "type": "bulleted_list_item",
                    "bulleted_list_item": {
                        "rich_text": [{"type": "text", "text": {"content": line[2:]}}]
                    }
                })
            elif line.strip():
                blocks.append({
                    "object": "block",
                    "type": "paragraph",
                    "paragraph": {
                        "rich_text": [{"type": "text", "text": {"content": line}}]
                    }
                })
        
        return blocks
